name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          bundler-cache: true
      - name: Set up db schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          bundler-cache: true
      - name: Rubocop
        run: bin/rubocop --parallel
